sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: vxGCB6qoaCxGtE/M8c+FMk6cJ1kC0XbWlapHPrmY0kNcvYpvf4BF+pnK0aVBmkylKTaUzEx0+pN9bGXkmscUm304wVdqsXkKEr5bw9qdaZe6EBlJSXJNHjj+/K8CjOh0Vb1GAkNzZZb20+REeFelyZt9JfaddasG8woO0ZwDKdrlAEKlDJuA6/XaOUBWJ7+K1OYcWlNfQGoTZ9bnTSXJEdGElmBCAayasqj/oEgLvbJR60lYD2egs2RnL+o44p4HgqH1IJcUKuqRVLYVA0OebCa/q/Ie9EKHHWqKVk0XQD+tz1/AdC0XYWRzmjw6tu1KF7C4BaqCfEv5doDXOQWiMPp1xBq553xNrBXmyyPxgV247cabO/TEbes8a2VzBgDCVyo+NhvbuVbxLBU8xUy60voOLcOFsjlisF0mHWXDgPVQU8YGRDooH0C+g50NghZ4N40qFF8K1pFW4KxRGsHl8HHPOMGZBtm5cbYizxAMO0xKiO6scAGrK5uJW8DXWKHRAwH0qYmZ0TY17LKox9QfwIuN0gg7OrZNxFvgcDfZVWWyOPd31+THfyrrrwBsD6/yQq9tNF2aVDsBPFWVPzy8z1guMQ2mQ2joQyp3k2T4gDRXIM6K8z+XRdLzvV0uuOE2wQ1Ju2XoThRvPYw93HU45k8INArGBaw6pQLI7yq37ag=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Moonbeams-from-the-Larger-Lunacy_4064
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy